# Generated by Django 4.1 on 2022-10-15 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_refeicao_opcao_novarefeicao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opcao',
            name='paciente',
        ),
    ]
