# Generated by Django 4.1.1 on 2022-11-03 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0006_alter_novarefeicao_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcao',
            name='refeicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.novarefeicao'),
        ),
    ]
